work_dir: work_dir/linear_eval/1_model300
weights: /home/liuyuex/Documents/CrosSCLR/work_dir/crossclr_3views/byol_xview_frame50_channel16_epoch300/epoch300_model.pt
ignore_weights: [online_network.fc, online_network_motion.fc, online_network_bone.fc, target_network, target_network_motion, target_network_bone, queue, queue_motion, queue_bone]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /home/liuyuex/Documents/CrosSCLR/data/HR-ShanghaiTech/train_position.npy
  label_path: /home/liuyuex/Documents/CrosSCLR/data/HR-ShanghaiTech/train_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /home/liuyuex/Documents/CrosSCLR/data/HR-ShanghaiTech/test_position.npy
  label_path: /home/liuyuex/Documents/CrosSCLR/data/HR-ShanghaiTech/test_label.pkl
  shear_amplitude: -1
  temperal_padding_ratio: -1
  mmap: True

# model
model: net.byol_3views.BYOL
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  feature_dim: 128
#  queue_size: 32768
#  momentum: 0.999
#  Temperature: 0.07
#  mlp: True

  in_channels: 2
  hidden_channels: 16
  hidden_dim: 256
  num_class: 128
  dropout: 0.5
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 0
view: 'all'
phase: 'test'


# log
save_interval: -1
eval_interval: 5
